[package]
name = "ipc"
version = "0.1.0"
authors = ["inkooboo <inkooboo@gmail.com>"]

[target.'cfg(not(windows))'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
kernel32-sys = "0.2"
winapi = "0.2"
